/*
--删除用户
drop user DLGIS CASCADE;
drop user SDE CASCADE; 
drop user MMS CASCADE;
drop user DLSYS CASCADE;
drop user DLMIS CASCADE;
drop user ULOG CASCADE;
drop user DLINIT CASCADE;
drop user UMSTAT CASCADE;
drop user DLTRANS CASCADE;
drop user DLHIST CASCADE;
*/


--设置DBMS_LOCK和DBMS_PIPE两个包的权限，必须以SYS用户登录
grant execute on dbms_pipe to public;
grant execute on dbms_lock to public;

--创建用户
CREATE USER DLINIT PROFILE "DEFAULT"
    IDENTIFIED BY "cyberway" DEFAULT TABLESPACE DLSYS
    ACCOUNT UNLOCK;
GRANT CONNECT TO DLINIT;

CREATE USER DLSYS PROFILE "DEFAULT"
    IDENTIFIED BY "dlsys" DEFAULT TABLESPACE DLSYS
    ACCOUNT UNLOCK;
GRANT CONNECT TO DLSYS;
GRANT DBA TO DLSYS;
GRANT ALTER ANY TABLE TO DLSYS;
GRANT CREATE ANY INDEX TO DLSYS;
GRANT CREATE ANY PROCEDURE  TO DLSYS;
GRANT CREATE ANY TABLE TO DLSYS;
GRANT CREATE ANY TRIGGER TO DLSYS;
GRANT DELETE ANY TABLE TO DLSYS;
GRANT DROP ANY INDEX TO DLSYS;
GRANT DROP ANY PROCEDURE TO DLSYS;
GRANT DROP ANY TABLE TO DLSYS;
GRANT DROP ANY TRIGGER TO DLSYS;
GRANT EXECUTE ANY PROCEDURE TO DLSYS; 
GRANT INSERT ANY TABLE TO DLSYS;
GRANT SELECT ANY TABLE TO DLSYS;
GRANT UPDATE ANY TABLE TO DLSYS;
GRANT ALTER ANY PROCEDURE TO DLSYS;
GRANT CREATE ANY VIEW TO DLSYS;
GRANT SELECT ANY SEQUENCE TO DLSYS;

CREATE USER DLMIS PROFILE "DEFAULT"
    IDENTIFIED BY "dlmis" DEFAULT TABLESPACE DLMIS
    ACCOUNT UNLOCK;
GRANT CONNECT TO DLMIS;
GRANT DBA TO DLMIS;
GRANT CREATE PROCEDURE to DLMIS;
GRANT CREATE SESSION TO DLMIS;
GRANT CREATE TABLE TO DLMIS;
GRANT CREATE TRIGGER TO DLMIS;
GRANT CREATE TYPE TO DLMIS;
GRANT CREATE VIEW TO DLMIS;
GRANT DELETE ANY TABLE TO DLMIS;
GRANT DEBUG ANY PROCEDURE TO DLMIS;
GRANT DROP ANY PROCEDURE TO DLMIS;
GRANT DROP ANY TABLE TO DLMIS;
GRANT DROP ANY TRIGGER TO DLMIS;
GRANT DROP ANY TYPE TO DLMIS;
GRANT EXECUTE ANY PROCEDURE TO DLMIS; 
GRANT INSERT ANY TABLE TO DLMIS;
GRANT SELECT ANY TABLE TO DLMIS;
GRANT UPDATE ANY TABLE TO DLMIS;

CREATE USER UMSTAT PROFILE "DEFAULT"
    IDENTIFIED BY "umstat" DEFAULT TABLESPACE UMSTAT
    ACCOUNT UNLOCK;
GRANT CONNECT TO UMSTAT;
GRANT DBA TO UMSTAT;
GRANT CREATE PROCEDURE to UMSTAT;
GRANT CREATE SESSION TO UMSTAT;
GRANT CREATE TABLE TO UMSTAT;
GRANT CREATE TRIGGER TO UMSTAT;
GRANT CREATE TYPE TO UMSTAT;
GRANT CREATE VIEW TO UMSTAT;
GRANT DELETE ANY TABLE TO UMSTAT;
GRANT DEBUG ANY PROCEDURE TO UMSTAT;
GRANT DROP ANY PROCEDURE TO UMSTAT;
GRANT DROP ANY TABLE TO UMSTAT;
GRANT DROP ANY TRIGGER TO UMSTAT;
GRANT DROP ANY TYPE TO UMSTAT;
GRANT EXECUTE ANY PROCEDURE TO UMSTAT; 
GRANT INSERT ANY TABLE TO UMSTAT;
GRANT SELECT ANY TABLE TO UMSTAT;
GRANT UPDATE ANY TABLE TO UMSTAT;

CREATE USER MMS PROFILE "DEFAULT"
    IDENTIFIED BY "mms" DEFAULT TABLESPACE MMS
    ACCOUNT UNLOCK;
GRANT CONNECT TO MMS;
GRANT DBA TO MMS;
GRANT ALTER ANY TABLE TO MMS;
GRANT CREATE ANY INDEX TO MMS;
GRANT CREATE ANY PROCEDURE  TO MMS;
GRANT CREATE ANY TABLE TO MMS;
GRANT CREATE ANY TRIGGER TO MMS;
GRANT DELETE ANY TABLE TO MMS;
GRANT DROP ANY INDEX TO MMS;
GRANT DROP ANY PROCEDURE TO MMS;
GRANT DROP ANY TABLE TO MMS;
GRANT DROP ANY TRIGGER TO MMS;
GRANT EXECUTE ANY PROCEDURE TO MMS; 
GRANT INSERT ANY TABLE TO MMS;
GRANT SELECT ANY TABLE TO MMS;
GRANT UPDATE ANY TABLE TO MMS;
GRANT ALTER ANY PROCEDURE TO MMS;
GRANT CREATE ANY VIEW TO MMS;
GRANT SELECT ANY SEQUENCE TO MMS;

CREATE USER DLGIS PROFILE "DEFAULT"
    IDENTIFIED BY "dlgis" DEFAULT TABLESPACE DLGIS
    ACCOUNT UNLOCK;
GRANT CONNECT TO DLGIS;
GRANT DBA TO DLGIS;
GRANT ALTER ANY TABLE TO DLGIS;
GRANT CREATE ANY INDEX TO DLGIS;
GRANT CREATE ANY PROCEDURE  TO DLGIS;
GRANT CREATE ANY TABLE TO DLGIS;
GRANT CREATE ANY TRIGGER TO DLGIS;
GRANT DELETE ANY TABLE TO DLGIS;
GRANT DROP ANY INDEX TO DLGIS;
GRANT DROP ANY PROCEDURE TO DLGIS;
GRANT DROP ANY TABLE TO DLGIS;
GRANT DROP ANY TRIGGER TO DLGIS;
GRANT EXECUTE ANY PROCEDURE TO DLGIS; 
GRANT INSERT ANY TABLE TO DLGIS;
GRANT SELECT ANY TABLE TO DLGIS;
GRANT UPDATE ANY TABLE TO DLGIS;
GRANT ALTER ANY PROCEDURE TO DLGIS;
GRANT CREATE ANY VIEW TO DLGIS;

CREATE USER SDE PROFILE "DEFAULT"
    IDENTIFIED BY "sde" DEFAULT TABLESPACE SDE
    ACCOUNT UNLOCK;
GRANT CONNECT TO SDE;
GRANT DBA TO SDE;
GRANT ALTER ANY TABLE TO SDE;
GRANT CREATE ANY INDEX TO SDE;
GRANT CREATE ANY PROCEDURE  TO SDE;
GRANT CREATE ANY TABLE TO SDE;
GRANT CREATE ANY TRIGGER TO SDE;
GRANT DELETE ANY TABLE TO SDE;
GRANT DROP ANY INDEX TO SDE;
GRANT DROP ANY PROCEDURE TO SDE;
GRANT DROP ANY TABLE TO SDE;
GRANT DROP ANY TRIGGER TO SDE;
GRANT EXECUTE ANY PROCEDURE TO SDE; 
GRANT INSERT ANY TABLE TO SDE;
GRANT SELECT ANY TABLE TO SDE;
GRANT UPDATE ANY TABLE TO SDE;
GRANT ALTER ANY PROCEDURE TO SDE;
GRANT CREATE  ANY VIEW to SDE;
GRANT CREATE SESSION to SDE;
GRANT CREATE SEQUENCE to SDE;
GRANT CREATE TYPE to SDE;
GRANT CREATE LIBRARY to SDE;
GRANT CREATE PUBLIC SYNONYM to SDE;
GRANT CREATE OPERATOR to SDE;
GRANT CREATE INDEXTYPE to SDE;
GRANT DROP PUBLIC SYNONYM to SDE;
GRANT UNLIMITED TABLESPACE to SDE;
GRANT ADMINISTER DATABASE TRIGGER to SDE;

--需要用sys用户登陆

CREATE USER ULOG PROFILE "DEFAULT"
    IDENTIFIED BY ULOG DEFAULT TABLESPACE USERS
    ACCOUNT UNLOCK;
GRANT CONNECT TO ULOG;
GRANT RESOURCE TO ULOG;
GRANT ALL ON SYS.DBMS_PIPE TO ULOG;
GRANT CREATE PUBLIC SYNONYM TO ULOG;
GRANT DROP PUBLIC SYNONYM TO ULOG;
GRANT EXECUTE ON SYS.DBMS_SYSTEM TO ULOG;
GRANT EXECUTE ON SYS.DBMS_SYSTEM TO ULOG;



CREATE USER DLHIST PROFILE "DEFAULT"
    IDENTIFIED BY "dlhist" DEFAULT TABLESPACE DLHIST 
    ACCOUNT UNLOCK;
GRANT CONNECT TO DLHIST ;
GRANT DBA TO DLHIST ;
GRANT ALTER ANY TABLE TO DLHIST;
GRANT CREATE ANY INDEX TO DLHIST;
GRANT CREATE ANY PROCEDURE  TO DLHIST;
GRANT CREATE ANY TABLE TO DLHIST;
GRANT CREATE ANY TRIGGER TO DLHIST;
GRANT DELETE ANY TABLE TO DLHIST;
GRANT DROP ANY INDEX TO DLHIST;
GRANT DROP ANY PROCEDURE TO DLHIST;
GRANT DROP ANY TABLE TO DLHIST;
GRANT DROP ANY TRIGGER TO DLHIST;
GRANT EXECUTE ANY PROCEDURE TO DLHIST;
GRANT INSERT ANY TABLE TO DLHIST;
GRANT SELECT ANY TABLE TO DLHIST;
GRANT UPDATE ANY TABLE TO DLHIST;
GRANT ALTER ANY PROCEDURE TO DLHIST;
GRANT CREATE  ANY VIEW to DLHIST;
GRANT CREATE SESSION to DLHIST;
GRANT CREATE SEQUENCE to DLHIST;
GRANT CREATE TYPE to DLHIST;
GRANT CREATE LIBRARY to DLHIST;
GRANT CREATE PUBLIC SYNONYM to DLHIST;
GRANT CREATE OPERATOR to DLHIST;
GRANT CREATE INDEXTYPE to DLHIST;
GRANT DROP PUBLIC SYNONYM to DLHIST;
GRANT UNLIMITED TABLESPACE to DLHIST;
GRANT ADMINISTER DATABASE TRIGGER to DLHIST;


CREATE USER DLTRANS PROFILE "DEFAULT"
    IDENTIFIED BY "dltrans" DEFAULT TABLESPACE DLTRANS
    ACCOUNT UNLOCK;
GRANT CONNECT TO DLTRANS;
GRANT DBA TO DLTRANS;
GRANT ALTER ANY TABLE TO DLTRANS;
GRANT CREATE ANY INDEX TO DLTRANS;
GRANT CREATE ANY PROCEDURE  TO DLTRANS;
GRANT CREATE ANY TABLE TO DLTRANS;
GRANT CREATE ANY TRIGGER TO DLTRANS;
GRANT DELETE ANY TABLE TO DLTRANS;
GRANT DROP ANY INDEX TO DLTRANS;
GRANT DROP ANY PROCEDURE TO DLTRANS;
GRANT DROP ANY TABLE TO DLTRANS;
GRANT DROP ANY TRIGGER TO DLTRANS;
GRANT EXECUTE ANY PROCEDURE TO DLTRANS;
GRANT INSERT ANY TABLE TO DLTRANS;
GRANT SELECT ANY TABLE TO DLTRANS;
GRANT UPDATE ANY TABLE TO DLTRANS;
GRANT ALTER ANY PROCEDURE TO DLTRANS;
GRANT CREATE  ANY VIEW to DLTRANS;
GRANT CREATE SESSION to DLTRANS;
GRANT CREATE SEQUENCE to DLTRANS;
GRANT CREATE TYPE to DLTRANS;
GRANT CREATE LIBRARY to DLTRANS;
GRANT CREATE PUBLIC SYNONYM to DLTRANS;
GRANT CREATE OPERATOR to DLTRANS;
GRANT CREATE INDEXTYPE to DLTRANS;
GRANT DROP PUBLIC SYNONYM to DLTRANS;
GRANT UNLIMITED TABLESPACE to DLTRANS;
GRANT ADMINISTER DATABASE TRIGGER to DLTRANS;

exit